export const worksObj = {
  id: 'works',
  lightBg: true,
  topLine: 'Trabalhos',
  headlineOne: 'Anel da Argentina',
  descriptionOne: 'Anel de safira com ouro 18k',
  headlineTwo: 'Aliança da Tasmânia',
  descriptionTwo: 'Anel de diamantes',
  headlineThree: 'Aneis Personalizáveis',
  descriptionThree: 'Faça seu próprio estilo',
  img01: require('../../images/image-4.png'),
  img02: require('../../images/image-5.png'),
  img03: require('../../images/image-1.png'),
  alt: 'Diamante',
};